### ISSUE TITLE
groups.search('group') method is documented but it is not present

### ISSUE THREAD

**Issue by aruiz** [gpocentek/python-gitlab#255]
when I try to use the documented groups.search() method I get this error:

> prj = self.gl.groups.search(grp)[0].projects.search(repo)[0]
> AttributeError: 'GroupProjectManager' object has no attribute 'search'

**Comment by gpocentek** [comment]
The error is not related to the ``Group`` manager, but to the ``GroupProject`` manager.

There should be a search method on this object anyway, so this is still a bug.

**Comment by gpocentek** [comment]
Note: this change will probably not give you the result you expect, because the search method doesn't consider the previous search result (group_id), i.e using ``self.gl.projects.search(repo)[0]`` will give the same (and probably unwanted) result.

https://gitlab.com/gitlab-org/gitlab-ce/issues/23185 is probably what's needed here.

**Comment by hjdr4** [comment]
Using API v4:
self.group=self.gitlabApi.groups.search(self.project.name)[0]
=>
AttributeError, 'GroupManager' object has no attribute 'search'

How do I get a group by name ?

*v3 group visibility does not work

**Comment by adinriv** [comment]
You can do a search with `gl.groups.list(search='group-name')`.  But that is not documented.  I found it in another comment.
